projects/Project 10/Projek1/Projek1/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todolist.urls')),
]

projects/Project 10/Projek1/todolist/urls.py
from django.urls import path
from .views import todolist, update, delete



app_name = "todolist"

urlpatterns = [
    path('',todolist,name='aplikacja to do list'),
    path('update/<str:pk>/',update,name='taskupdate'),
    path('delete/<str:pk>/',delete,name='delet')
]

projects/Project 10/Projek1/todolist/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title


projects/Project 10/Projek1/todolist/forms.py
from socket import fromshare
from django import forms
from django.forms import ModelForm
from .models import Task

class TasksForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = '__all__'



projects/Project 10/Projek1/todolist/views.py
import re
from django.shortcuts import render,redirect
from .models import Task
from .forms import TasksForm

# Create your views here.

def todolist(request):

    tasks = Task.objects.all()
    form = TasksForm()
    context = {'tasks':tasks,'form':form}
    
    if request.method == 'POST':
        form = TasksForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/')

    return render(request,'main/todolist.html',context)

def update(request, pk):
    task = Task.objects.get(id=pk)
    form = TasksForm(instance=task)
    context = {'form':form}
    if request.method == 'POST':
        form = TasksForm(request.POST,instance=task)
        if form.is_valid():
            form.save()
            return redirect('/')

    return render(request, 'main/update.html',context)

def delete(request,pk):
    item = Task.objects.get(pk=pk)

    if request.method == 'POST':
        item.delete()
        return redirect('/')

    return render(request,'main/delete.html',context={'item':item})

projects/Project 10/Projek1/todolist/templates/main/delete.html
delete {{item}}?
<a href="{% url 'todolist:aplikacja to do list' %}">Don't</a>

<form method="POST" action="">
    {% csrf_token %}
    <input type="submit" name="GO">
</form>




projects/Project 10/Projek1/todolist/templates/main/todolist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tytul</title>
    
    
    <style>
        body{
        background-color: rgb(0, 0, 0);
        }
        
        #nav {
        
        background-color: rgb(0, 0, 0);
        text-align: center;
        letter-spacing: 2px;
        text-shadow: blue 4px 4px;
        color: wheat;
        font-size: x-large;
        
        }
        
        #left{
        background-color: darkblue;
        float: left;
        width: 300px;
        height: 625px;
        border: wheat solid 2px;
        color: wheat;
        font-size: 25px;
        }
        
        #main{
        
        background-color: rgb(86, 85, 82);
        width: 1000px;
        height: 625px;
        float: left;
        border: wheat solid 2px;
        
        }
        
        li{
        margin: 10px;
        font-size: x-large;
        }
        
        #list {
        
        font-size:  45px;
        margin-bottom: 20px;

        }

        a {
            color: wheat
        }

        a:link {
  text-decoration: none;
}

a:visited {
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

a:active {
  text-decoration: underline;
}
     #dodaj{
        height: 150px;
        background-color: rgb(86, 85, 82);
        text-align: center;
        color: wheat;
        font-size: large;
     }   

     #taskss{
        background-color: rgb(191, 191, 196);
        height:  453px;
     }
     #delute{
        font-size: small;
        width: 37px;
        

     }
        
        
        </style>

    
</head>
<body>

    <div id ='nav'>
        <h1>TO DO LIST</h1>
    </div>

    <div id="left">

        <ul>
            
            <div id="list">Active lists: </div>
            {% for task in tasks %}
            <a href="{% url 'todolist:taskupdate' task.id %}"><li>

                {% if task.complete is True %}
                <strike>{{task}}</strike>
                {% else %}
                {{task}}
                {% endif %}
            </a>
            <div id='delute'><a href="{% url 'todolist:delet' task.id %}">Delete</a></div>
        </li>
            {% empty %}
             -- empty list --
            {% endfor %}

        </ul>


    </div>

    <div id='main'>

        <div id="dodaj">

            <h2>Add a new list</h2>

        <form method="POST" action="/">
            {% csrf_token %}
            {{form.title}}
            <input type="submit" name="New Task">

        </form>

    </div>

        
        <div id="taskss">
            
        
        </div>


    </div>

</body>
</html>

projects/Project 10/Projek1/todolist/templates/main/update.html
<h3>Update</h3>

<form method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" name="taskupdate">
</form>